### ISSUE TITLE
S3 Bucket?

### ISSUE THREAD

**Issue by gamename** [octo-technology-downunder/sls-lambdas#1]
Hi,

I'm trying to use your billing reporter.  It looks *really* nice.

But, I'm confused on one point.  Are we supposed to create an S3 bucket with a billing report in it, or does the utility create it for us?  I'm referring to this section of the common properties.
```json
"s3": {
    "awsRegion": "ap-southeast-2",
    "keyPrefix": "XXXX/XXXXXX",
    "billingBucketName": "XXXXXXXXX",
    "reportFileName": "XXXXXXXXX.csv.gz",
    "manifestFileName": "XXXXXXXXX-Manifest.json"
  },
```

**Comment by ilya-v-trofimov** [comment]
@gamename , Thanks for opening this issue.
It's expected that AWS billing reports delivery to S3 bucket to be turned on.
Please follow the instructions from AWS on how to turn it on: [https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-getting-started.html#step-2](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-getting-started.html#step-2)
I've also updated README.md (Billing reporter settings configuration section, parameters table) to reflect this prerequisite
