### ISSUE TITLE
Default to USD?

### ISSUE THREAD

**Issue by gamename** [octo-technology-downunder/sls-lambdas#2]
Hi,

For BillingReporter, how do I set the currency to default to US dollars?  That is to say, what happens if no conversion is needed?  What do I set the following fields to?
```
"converter": {
    "converterUrl": "https://api.fixer.io/latest?base=AUD&symbols=USD",
    "currencySymbol" : "AUD $",
    "converterDefaultRate": 1,
    "converterDefaultCurrency" : "USD $"
  }
```

**Comment by ilya-v-trofimov** [comment]
Hi @gamename ,
Thanks for asking. 
Just leave converterUrl field blank, that should resolve to converterDefaultRate and converterDefaultCurrency values.

It might be a good idea to revisit converter section settings to make it more transparent.

**Comment by gamename** [comment]
Thank you, sir
